name: LDHD Dev CI/CD
on:
  # 1. 수동 실행 (Action 탭에서 버튼 클릭)
  workflow_dispatch:

  # 2. PR이 닫혔을 때 감지
  pull_request:
    types: [closed]
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest # (3).OS환경
    if: github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop')